# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
    ]
