# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('asses_type', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssesmentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(max_length=20)),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Assesment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=10)),
                ('Credit', models.FloatField(max_length=10)),
                ('year', models.IntegerField(max_length=2)),
                ('semester', models.IntegerField(max_length=2)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=2)),
                ('semester', models.IntegerField(max_length=2)),
                ('starting_date', models.DateField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=50)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('std_id', models.CharField(blank=True, max_length=15)),
                ('session', models.CharField(blank=True, max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.IntegerField(blank=True, max_length=2)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Department')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=2)),
                ('user_type', models.CharField(max_length=2)),
                ('address', models.TextField(null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.USER'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.USER'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Files'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='offeredcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.OfferedCourse'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Teacher'),
        ),
        migrations.AddField(
            model_name='assesmentmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Student'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='offeredcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.OfferedCourse'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Teacher'),
        ),
    ]
