# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0006_auto_20160528_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredcourse',
            name='courseTeacher',
            field=models.ManyToManyField(to='webportal.Teacher'),
        ),
    ]
