# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0007_offeredcourse_courseteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredcourse',
            name='courseTeacher',
        ),
        migrations.RemoveField(
            model_name='offeredcourse',
            name='studentCourseEnrollment',
        ),
        migrations.AddField(
            model_name='student',
            name='studentCourseEnrollment',
            field=models.ManyToManyField(to='webportal.OfferedCourse'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courseTeacher',
            field=models.ManyToManyField(to='webportal.OfferedCourse'),
        ),
    ]
