# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0008_auto_20160528_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offeredcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.OfferedCourse')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offeredcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.OfferedCourse')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentCourseEnrollment',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courseTeacher',
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Student'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webportal.Teacher'),
        ),
    ]
