# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0009_auto_20160528_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
