# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0011_auto_20160528_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='statis',
            field=models.IntegerField(default=-1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='statis',
            field=models.IntegerField(default=-1, max_length=2),
            preserve_default=False,
        ),
    ]
