# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0012_auto_20160602_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseteacher',
            old_name='statis',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='statis',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.FileField(upload_to=b'CourseMaterial/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'user/images/'),
        ),
    ]
